// <auto-generated>
//   Generated from schema/coimap.spec.mjs by schema/generate.mjs — DO NOT EDIT BY HAND.
//   Edit the spec and re-run `npm run schema`.
// </auto-generated>

namespace CoiMapper.Schema {

    public static class CoiMapSchema {
        public const int SchemaVersion = 1;
        public const string Manifest = "manifest.json";
        public const string Entities = "entities.json";
        public const string Networks = "networks.json";
        public const string Protos = "protos.json";
        public const string Thumbnail = "thumbnail.jpg";
        public const string PlaneDir = "planes/";
    }

    public static class DesignationBits {
        public const byte Mine = 1;
        public const byte Dump = 2;
        public const byte Forestry = 4;
        public const byte Surface = 8;
        public const byte Unreachable = 16;
    }

    public enum EntityState { Unknown, Constructing, Operating, Idle, Paused, Disabled, Broken, Deconstructing }

    public enum TransportKind { Unknown, Conveyor, Pipe }

    public enum NetworkKind { Electricity, MechanicalShaft, Rail }

    /// <summary>Per-tile raster planes; name, dtype and archive path.</summary>
    public static class Planes {
        public struct Def { public string Name; public string Dtype; public bool Optional;
            public Def(string n, string d, bool o) { Name = n; Dtype = d; Optional = o; }
            public string File { get { return CoiMapSchema.PlaneDir + Name + "." + Dtype; } } }
        public static readonly Def[] All = new Def[] {
            new Def("height", "u16", false),
            new Def("surface", "u8", false),
            new Def("material", "u8", true),
            new Def("deposit", "u8", true),
            new Def("depositAmount", "u16", true),
            new Def("designation", "u8", true),
            new Def("occupancy", "u8", true),
        };
    }

    public static class CategoryColors {
        public static string For(string category) {
            switch (category) {
                case "Mining": return "#c2703a";
                case "Smelting": return "#d4553a";
                case "Chemistry": return "#7d55b8";
                case "Manufacture": return "#3f7fb8";
                case "Power": return "#e0b13a";
                case "Storage": return "#6b7a86";
                case "Transport": return "#4a9e6b";
                case "Farming": return "#5aa03c";
                case "Settlement": return "#d189b0";
                case "Fluid": return "#3aa9c2";
                default: return "#8a8a8a";
            }
        }
    }

    public sealed class Manifest {
        /// <summary>Bumped on any breaking format change.</summary>
        public int SchemaVersion;
        /// <summary>Mod name and version that produced this file.</summary>
        public string Generator;
        /// <summary>ISO-8601 UTC timestamp.</summary>
        public string GeneratedAt;
        public GameInfo Game;
        public MapInfo Map;
        /// <summary>Which raster planes this file actually contains.</summary>
        public PlaneInfo[] Planes;
        /// <summary>Legend for the surface plane.</summary>
        public Surface[] Surfaces;
        /// <summary>Legend for the deposit plane.</summary>
        public Deposit[] Deposits;
        public Counts Counts;

        public void WriteTo(JsonWriter w) {
            w.BeginObject();
            w.Name("schemaVersion").Value(SchemaVersion);
            w.Name("generator").Value(Generator);
            w.Name("generatedAt").Value(GeneratedAt);
            w.Name("game"); Game.WriteTo(w);
            w.Name("map"); Map.WriteTo(w);
            w.Name("planes").BeginArray(); foreach (var v in Planes ?? new PlaneInfo[0]) { v.WriteTo(w); } w.EndArray();
            w.Name("surfaces").BeginArray(); foreach (var v in Surfaces ?? new Surface[0]) { v.WriteTo(w); } w.EndArray();
            w.Name("deposits").BeginArray(); foreach (var v in Deposits ?? new Deposit[0]) { v.WriteTo(w); } w.EndArray();
            w.Name("counts"); Counts.WriteTo(w);
            w.EndObject();
        }
    }

    public sealed class GameInfo {
        /// <summary>e.g. "0.8.2c".</summary>
        public string Version;
        public int SaveVersion;
        public string MapName;

        public void WriteTo(JsonWriter w) {
            w.BeginObject();
            w.Name("version").Value(Version);
            w.Name("saveVersion").Value(SaveVersion);
            w.Name("mapName").Value(MapName);
            w.EndObject();
        }
    }

    public sealed class MapInfo {
        /// <summary>Tiles along X.</summary>
        public int Width;
        /// <summary>Tiles along Y.</summary>
        public int Height;
        /// <summary>Height plane value 0 maps to this world height.</summary>
        public float MinHeight;
        /// <summary>Height plane value 65535 maps to this world height.</summary>
        public float MaxHeight;

        public void WriteTo(JsonWriter w) {
            w.BeginObject();
            w.Name("width").Value(Width);
            w.Name("height").Value(Height);
            w.Name("minHeight").Value(MinHeight);
            w.Name("maxHeight").Value(MaxHeight);
            w.EndObject();
        }
    }

    public sealed class PlaneInfo {
        public string Name;
        /// <summary>"u8" | "u16".</summary>
        public string Dtype;
        /// <summary>Path inside the archive.</summary>
        public string File;

        public void WriteTo(JsonWriter w) {
            w.BeginObject();
            w.Name("name").Value(Name);
            w.Name("dtype").Value(Dtype);
            w.Name("file").Value(File);
            w.EndObject();
        }
    }

    public sealed class Counts {
        public int Entities;
        public int Transports;
        public int Edges;
        public int Protos;

        public void WriteTo(JsonWriter w) {
            w.BeginObject();
            w.Name("entities").Value(Entities);
            w.Name("transports").Value(Transports);
            w.Name("edges").Value(Edges);
            w.Name("protos").Value(Protos);
            w.EndObject();
        }
    }

    public sealed class Surface {
        /// <summary>Value stored in the surface plane.</summary>
        public int Id;
        /// <summary>Display name, e.g. "Grass".</summary>
        public string Name;
        /// <summary>Base fill as "#rrggbb"; hillshading is applied on top.</summary>
        public string Color;
        /// <summary>True for ocean and water surfaces.</summary>
        public bool Water;

        public void WriteTo(JsonWriter w) {
            w.BeginObject();
            w.Name("id").Value(Id);
            w.Name("name").Value(Name);
            w.Name("color").Value(Color);
            w.Name("water").Value(Water);
            w.EndObject();
        }
    }

    public sealed class Deposit {
        /// <summary>Value stored in the deposit plane; 0 means none.</summary>
        public int Id;
        public string Name;
        public string Color;

        public void WriteTo(JsonWriter w) {
            w.BeginObject();
            w.Name("id").Value(Id);
            w.Name("name").Value(Name);
            w.Name("color").Value(Color);
            w.EndObject();
        }
    }

    public sealed class Entity {
        /// <summary>Stable in-game entity id.</summary>
        public int Id;
        /// <summary>Prototype id; key into protos.json.</summary>
        public string Proto;
        /// <summary>Tile X of the footprint origin.</summary>
        public int X;
        /// <summary>Tile Y of the footprint origin.</summary>
        public int Y;
        /// <summary>Footprint width in tiles, after rotation.</summary>
        public int W;
        /// <summary>Footprint height in tiles, after rotation.</summary>
        public int H;
        /// <summary>Rotation, 0-3 (quarter turns clockwise).</summary>
        public int Rot;
        public EntityState State;

        public void WriteTo(JsonWriter w) {
            w.BeginObject();
            w.Name("id").Value(Id);
            w.Name("proto").Value(Proto);
            w.Name("x").Value(X);
            w.Name("y").Value(Y);
            w.Name("w").Value(W);
            w.Name("h").Value(H);
            w.Name("rot").Value(Rot);
            w.Name("state").Value(State.ToString());
            w.EndObject();
        }
    }

    public sealed class Transport {
        public int Id;
        public string Proto;
        public TransportKind Kind;
        /// <summary>Flat [x0,y0,x1,y1,...] tile coordinates.</summary>
        public int[] Points;

        public void WriteTo(JsonWriter w) {
            w.BeginObject();
            w.Name("id").Value(Id);
            w.Name("proto").Value(Proto);
            w.Name("kind").Value(Kind.ToString());
            w.Name("points").BeginArray(); foreach (var v in Points ?? new int[0]) { w.Value(v); } w.EndArray();
            w.EndObject();
        }
    }

    public sealed class NetworkEdge {
        public NetworkKind Kind;
        /// <summary>Entity id.</summary>
        public int A;
        /// <summary>Entity id.</summary>
        public int B;

        public void WriteTo(JsonWriter w) {
            w.BeginObject();
            w.Name("kind").Value(Kind.ToString());
            w.Name("a").Value(A);
            w.Name("b").Value(B);
            w.EndObject();
        }
    }

    public sealed class Networks {
        public Transport[] Transports;
        public NetworkEdge[] Edges;

        public void WriteTo(JsonWriter w) {
            w.BeginObject();
            w.Name("transports").BeginArray(); foreach (var v in Transports ?? new Transport[0]) { v.WriteTo(w); } w.EndArray();
            w.Name("edges").BeginArray(); foreach (var v in Edges ?? new NetworkEdge[0]) { v.WriteTo(w); } w.EndArray();
            w.EndObject();
        }
    }

    public sealed class Proto {
        public string Id;
        /// <summary>Human-readable display name.</summary>
        public string Name;
        /// <summary>Grouping used for colouring and filters.</summary>
        public string Category;
        /// <summary>Fallback fill as "#rrggbb".</summary>
        public string Color;
        /// <summary>Unrotated footprint width.</summary>
        public int W;
        /// <summary>Unrotated footprint height.</summary>
        public int H;

        public void WriteTo(JsonWriter w) {
            w.BeginObject();
            w.Name("id").Value(Id);
            w.Name("name").Value(Name);
            w.Name("category").Value(Category);
            w.Name("color").Value(Color);
            w.Name("w").Value(W);
            w.Name("h").Value(H);
            w.EndObject();
        }
    }

}