#!/usr/bin/env node
/**
 * Emits TypeScript and C# bindings from `coimap.spec.mjs`.
 *   node schema/generate.mjs
 * Generated files are committed so neither side needs the generator to build.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import * as S from './coimap.spec.mjs';

const BANNER = (src) => `// <auto-generated>
//   Generated from schema/coimap.spec.mjs by schema/generate.mjs — DO NOT EDIT BY HAND.
//   Edit the spec and re-run \`npm run schema\`.
// </auto-generated>
`;

const isEnum = (t) => Object.hasOwn(S.ENUMS, t);
const isStruct = (t) => Object.hasOwn(S.STRUCTS, t);
const write = (path, body) => { mkdirSync(dirname(path), { recursive: true }); writeFileSync(path, body); console.log(`  ${path}`); };
const doc = (d, indent) => (d ? `${indent}/** ${d} */\n` : '');

// ── TypeScript ───────────────────────────────────────────────────────────────
const TS_PRIM = { int: 'number', float: 'number', bool: 'boolean', string: 'string', 'int[]': 'number[]' };
const tsType = (t) =>
  TS_PRIM[t] ?? (t.endsWith('[]') ? `${tsType(t.slice(0, -2))}[]` : t);

function generateTypeScript() {
  const out = [BANNER()];

  out.push(`export const SCHEMA_VERSION = ${S.SCHEMA_VERSION};\n`);
  out.push(`export const MEMBERS = ${JSON.stringify(S.MEMBERS, null, 2)} as const;\n`);

  for (const [name, values] of Object.entries(S.ENUMS)) {
    out.push(`export type ${name} = ${values.map((v) => `'${v}'`).join(' | ')};`);
    out.push(`export const ${name}Values = [${values.map((v) => `'${v}'`).join(', ')}] as const;\n`);
  }

  out.push(`/** Per-tile raster planes, row-major, width*height elements each. */`);
  out.push(`export const PLANES = {`);
  for (const [name, p] of Object.entries(S.PLANES)) {
    out.push(`${doc(p.doc, '  ')}  ${name}: { dtype: '${p.dtype}', optional: ${p.optional} },`);
  }
  out.push(`} as const;\n`);
  out.push(`export type PlaneName = keyof typeof PLANES;\n`);

  out.push(`/** Typed-array constructor for each plane dtype. */`);
  out.push(`export const DTYPE_ARRAY = { u8: Uint8Array, u16: Uint16Array } as const;`);
  out.push(`export type Dtype = keyof typeof DTYPE_ARRAY;\n`);

  out.push(`export const DESIGNATION_BITS = ${JSON.stringify(S.DESIGNATION_BITS, null, 2)} as const;\n`);
  out.push(`export const CATEGORY_COLORS: Record<string, string> = ${JSON.stringify(S.CATEGORY_COLORS, null, 2)};\n`);

  for (const [name, fields] of Object.entries(S.STRUCTS)) {
    out.push(`export interface ${name} {`);
    for (const f of fields) out.push(`${doc(f.doc, '  ')}  ${f.name}: ${tsType(f.type)};`);
    out.push(`}\n`);
  }

  return out.join('\n');
}

// ── C# ───────────────────────────────────────────────────────────────────────
const CS_PRIM = { int: 'int', float: 'float', bool: 'bool', string: 'string', 'int[]': 'int[]' };
const csType = (t) => CS_PRIM[t] ?? (t.endsWith('[]') ? `${csType(t.slice(0, -2))}[]` : t);
const pascal = (s) => s[0].toUpperCase() + s.slice(1);

/** JSON emitter fragment for one field. Enums serialise as strings. */
function csWriteField(f) {
  const prop = pascal(f.name);
  const base = f.type.replace(/\[\]$/, '');
  if (f.type.endsWith('[]')) {
    const each = isStruct(base) ? `v.WriteTo(w)` : isEnum(base) ? `w.Value(v.ToString())` : `w.Value(v)`;
    return `            w.Name("${f.name}").BeginArray(); foreach (var v in ${prop} ?? new ${csType(base)}[0]) { ${each}; } w.EndArray();`;
  }
  if (isStruct(f.type)) return `            w.Name("${f.name}"); ${prop}.WriteTo(w);`;
  if (isEnum(f.type)) return `            w.Name("${f.name}").Value(${prop}.ToString());`;
  return `            w.Name("${f.name}").Value(${prop});`;
}

function generateCSharp() {
  const out = [BANNER(), `namespace CoiMapper.Schema {\n`];

  out.push(`    public static class CoiMapSchema {`);
  out.push(`        public const int SchemaVersion = ${S.SCHEMA_VERSION};`);
  for (const [k, v] of Object.entries(S.MEMBERS)) out.push(`        public const string ${pascal(k)} = "${v}";`);
  out.push(`    }\n`);

  out.push(`    public static class DesignationBits {`);
  for (const [k, v] of Object.entries(S.DESIGNATION_BITS)) out.push(`        public const byte ${k} = ${v};`);
  out.push(`    }\n`);

  for (const [name, values] of Object.entries(S.ENUMS)) {
    out.push(`    public enum ${name} { ${values.join(', ')} }\n`);
  }

  out.push(`    /// <summary>Per-tile raster planes; name, dtype and archive path.</summary>`);
  out.push(`    public static class Planes {`);
  out.push(`        public struct Def { public string Name; public string Dtype; public bool Optional;`);
  out.push(`            public Def(string n, string d, bool o) { Name = n; Dtype = d; Optional = o; }`);
  out.push(`            public string File { get { return CoiMapSchema.PlaneDir + Name + "." + Dtype; } } }`);
  out.push(`        public static readonly Def[] All = new Def[] {`);
  for (const [name, p] of Object.entries(S.PLANES)) {
    out.push(`            new Def("${name}", "${p.dtype}", ${p.optional}),`);
  }
  out.push(`        };`);
  out.push(`    }\n`);

  out.push(`    public static class CategoryColors {`);
  out.push(`        public static string For(string category) {`);
  out.push(`            switch (category) {`);
  for (const [k, v] of Object.entries(S.CATEGORY_COLORS)) {
    if (k !== 'Other') out.push(`                case "${k}": return "${v}";`);
  }
  out.push(`                default: return "${S.CATEGORY_COLORS.Other}";`);
  out.push(`            }`);
  out.push(`        }`);
  out.push(`    }\n`);

  for (const [name, fields] of Object.entries(S.STRUCTS)) {
    out.push(`    public sealed class ${name} {`);
    for (const f of fields) {
      if (f.doc) out.push(`        /// <summary>${f.doc}</summary>`);
      out.push(`        public ${csType(f.type)} ${pascal(f.name)};`);
    }
    out.push(``);
    out.push(`        public void WriteTo(JsonWriter w) {`);
    out.push(`            w.BeginObject();`);
    for (const f of fields) out.push(csWriteField(f));
    out.push(`            w.EndObject();`);
    out.push(`        }`);
    out.push(`    }\n`);
  }

  out.push(`}`);
  return out.join('\n');
}

write(new URL('../web/src/coimap/schema.gen.ts', import.meta.url).pathname, generateTypeScript());
write(new URL('../mod/CoiMapper.Exporter/Schema/CoiMapSchema.gen.cs', import.meta.url).pathname, generateCSharp());
console.log('schema generated.');
