// <auto-generated>
//   Generated from schema/coimap.spec.mjs by schema/generate.mjs — DO NOT EDIT BY HAND.
//   Edit the spec and re-run `npm run schema`.
// </auto-generated>

export const SCHEMA_VERSION = 2;

export const MEMBERS = {
  "manifest": "manifest.json",
  "entities": "entities.json",
  "networks": "networks.json",
  "protos": "protos.json",
  "thumbnail": "thumbnail.jpg",
  "planeDir": "planes/"
} as const;

export type EntityState = 'Unknown' | 'Constructing' | 'Operating' | 'Idle' | 'Paused' | 'Disabled' | 'Broken' | 'Deconstructing';
export const EntityStateValues = ['Unknown', 'Constructing', 'Operating', 'Idle', 'Paused', 'Disabled', 'Broken', 'Deconstructing'] as const;

export type TransportKind = 'Unknown' | 'Conveyor' | 'Pipe';
export const TransportKindValues = ['Unknown', 'Conveyor', 'Pipe'] as const;

export type NetworkKind = 'Electricity' | 'MechanicalShaft' | 'Rail';
export const NetworkKindValues = ['Electricity', 'MechanicalShaft', 'Rail'] as const;

export type VehicleKind = 'Unknown' | 'Truck' | 'Excavator' | 'TreeHarvester' | 'TreePlanter' | 'Locomotive' | 'CargoWagon' | 'RocketTransporter';
export const VehicleKindValues = ['Unknown', 'Truck', 'Excavator', 'TreeHarvester', 'TreePlanter', 'Locomotive', 'CargoWagon', 'RocketTransporter'] as const;

/** Per-tile raster planes, row-major, width*height elements each. */
export const PLANES = {
  /** Terrain height, game units, per tile. */
  height: { dtype: 'u16', optional: false },
  /** Natural ground: topmost material slim id + 1, 0 = ocean. Index into manifest.surfaces. Despite the name this is NOT player-placed paving — see tileSurface. */
  surface: { dtype: 'u8', optional: false },
  /** Topmost terrain material slim id. */
  material: { dtype: 'u8', optional: true },
  /** Player-placed surface slim id; 0 = unpaved. Index into manifest.tileSurfaces. */
  tileSurface: { dtype: 'u8', optional: true },
  /** Virtual resource id present under this tile; 0 = none. */
  deposit: { dtype: 'u8', optional: true },
  /** Relative quantity of the deposit, 0-65535. */
  depositAmount: { dtype: 'u16', optional: true },
  /** Bitmask: 1=mine 2=dump 4=forestry 8=surface 16=unreachable. */
  designation: { dtype: 'u8', optional: true },
  /** Non-zero where any static entity occupies the tile. */
  occupancy: { dtype: 'u8', optional: true },
} as const;

export type PlaneName = keyof typeof PLANES;

/** Typed-array constructor for each plane dtype. */
export const DTYPE_ARRAY = { u8: Uint8Array, u16: Uint16Array } as const;
export type Dtype = keyof typeof DTYPE_ARRAY;

export const DESIGNATION_BITS = {
  "Mine": 1,
  "Dump": 2,
  "Forestry": 4,
  "Surface": 8,
  "Unreachable": 16
} as const;

export const CATEGORY_COLORS: Record<string, string> = {
  "Mining": "#c2703a",
  "Smelting": "#d4553a",
  "Chemistry": "#7d55b8",
  "Manufacture": "#3f7fb8",
  "Power": "#e0b13a",
  "Storage": "#6b7a86",
  "Transport": "#4a9e6b",
  "Farming": "#5aa03c",
  "Settlement": "#d189b0",
  "Fluid": "#3aa9c2",
  "Other": "#8a8a8a"
};

export interface Manifest {
  /** Bumped on any breaking format change. */
  schemaVersion: number;
  /** Mod name and version that produced this file. */
  generator: string;
  /** ISO-8601 UTC timestamp. */
  generatedAt: string;
  game: GameInfo;
  map: MapInfo;
  /** Which raster planes this file actually contains. */
  planes: PlaneInfo[];
  /** Legend for the surface plane. */
  surfaces: Surface[];
  /** Legend for the tileSurface plane. Absent in files written before that plane existed. */
  tileSurfaces: TileSurface[];
  /** Legend for the deposit plane. */
  deposits: Deposit[];
  /** The fleet, counted per prototype. Absent in files written before this existed. */
  vehicles: VehicleCensus;
  counts: Counts;
}

export interface GameInfo {
  /** e.g. "0.8.2c". */
  version: string;
  saveVersion: number;
  mapName: string;
}

export interface MapInfo {
  /** Tiles along X. */
  width: number;
  /** Tiles along Y. */
  height: number;
  /** Height plane value 0 maps to this world height. */
  minHeight: number;
  /** Height plane value 65535 maps to this world height. */
  maxHeight: number;
}

export interface PlaneInfo {
  name: string;
  /** "u8" | "u16". */
  dtype: string;
  /** Path inside the archive. */
  file: string;
}

export interface Counts {
  entities: number;
  transports: number;
  edges: number;
  protos: number;
}

export interface Surface {
  /** Value stored in the surface plane. */
  id: number;
  /** Display name, e.g. "Grass". */
  name: string;
  /** Base fill as "#rrggbb"; hillshading is applied on top. */
  color: string;
  /** True for ocean and water surfaces. */
  water: boolean;
}

export interface TileSurface {
  /** Value stored in the tileSurface plane; 0 means unpaved. */
  id: number;
  /** Display name, e.g. "Concrete". */
  name: string;
  /** Fill as "#rrggbb"; hillshading is applied on top. */
  color: string;
}

export interface Deposit {
  /** Value stored in the deposit plane; 0 means none. */
  id: number;
  name: string;
  color: string;
}

export interface VehicleCount {
  /** Prototype id. NOT a key into protos.json — see above. */
  proto: string;
  /** Display name, e.g. "Haul truck (dump) (Diesel)". The fuel variant is part of the game's own name. */
  name: string;
  kind: VehicleKind;
  /** Key into VehicleCensus.zones, or -1 for a machine that has no zone. Every road vehicle belongs to exactly one logistics zone — the default zone if the player never moved it — so -1 means train cars, which the game gives no zone at all, or an export whose zone manager would not resolve. */
  zone: number;
  count: number;
}

export interface VehicleZone {
  /** The game's own zone id; what VehicleCount.zone refers to. */
  id: number;
  /** Display name. The player's own name where they set one, else the game's. */
  name: string;
  /** The zone's colour in game, as "#rrggbb". Used as a swatch, not a fill. */
  color: string;
  /** True for the one zone the game creates itself and the player cannot remove. */
  isDefault: boolean;
}

export interface VehicleCensus {
  /** False when this export carries no census at all — either written by a mod build from before vehicles were exported, or the vehicle managers would not resolve. Distinct from a world that genuinely has none, which exports with an empty types list. */
  exported: boolean;
  /** One row per prototype *per zone* — the finest grain, so a panel can total it by kind or by zone without the format changing. Ordered by kind (the VehicleKind declaration order), then zone, then count descending, then name. The exporter fixes the order so two exports of the same world agree byte for byte. */
  types: VehicleCount[];
  /** The zones VehicleCount.zone refers to, default zone first and then the order the game holds them in; the UI groups by this order rather than re-sorting, so the writer stays the one place that decides it. Empty means zone data was not exported — a mod build from before zones, or a zone manager that would not resolve — and never means "this world has no zones", because the game always has a default zone and a manager that resolved always yields at least one. That is why zones need no `exported` flag of their own, unlike the census. */
  zones: VehicleZone[];
  /** Total road vehicles. */
  vehicles: number;
  /** Total locomotives and cargo wagons. */
  trainCars: number;
  /** Assembled trains; the cars counted above belong to these. */
  trains: number;
  /** The game's vehicle quota. 0 when unknown. */
  limit: number;
  /** Quota remaining. */
  limitLeft: number;
}

export interface Entity {
  /** Stable in-game entity id. */
  id: number;
  /** Prototype id; key into protos.json. */
  proto: string;
  /** Tile X of the footprint origin. */
  x: number;
  /** Tile Y of the footprint origin. */
  y: number;
  /** Footprint width in tiles, after rotation. */
  w: number;
  /** Footprint height in tiles, after rotation. */
  h: number;
  /** Rotation, 0-3 (quarter turns clockwise). */
  rot: number;
  state: EntityState;
  /** Occupied tiles as flat [dx,dy,...] offsets from (x,y). Empty when the entity fills its w*h box exactly, which is the common case for machines. Conveyors and pipes snake, so their bounding box is mostly empty and this lists the tiles they really cover. */
  tiles: number[];
}

export interface Transport {
  id: number;
  proto: string;
  kind: TransportKind;
  /** Flat [x0,y0,x1,y1,...] tile coordinates. */
  points: number[];
}

export interface NetworkEdge {
  kind: NetworkKind;
  /** Entity id. */
  a: number;
  /** Entity id. */
  b: number;
}

export interface Networks {
  transports: Transport[];
  edges: NetworkEdge[];
}

export interface Proto {
  id: string;
  /** Human-readable display name. */
  name: string;
  /** Grouping used for colouring and filters. */
  category: string;
  /** Fallback fill as "#rrggbb". */
  color: string;
  /** Unrotated footprint width. */
  w: number;
  /** Unrotated footprint height. */
  h: number;
}
